version: 2

jobs:
  py36:
    docker:
      - image: circleci/python:3.6

    steps: &test-steps
      - checkout

      - run:
          name: "Setup"
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python setup.py develop
            pip install black pytest
            
      - run:
          name: "Check code formatting"
          command: |
            . venv/bin/activate
            black --check sinter/

      - run:
          name: "Run tests"
          command: |
            . venv/bin/activate
            pytest

  py37:
    docker:
      - image: circleci/python:3.7

    steps: *test-steps

workflows:
  version: 2
  build-all:
    jobs:
      - py36
      - py37
